
CREATE TABLE REGIONS AS SELECT * FROM HR.REGIONS;
CREATE TABLE COUNTRIES AS SELECT * FROM HR.COUNTRIES;
CREATE TABLE LOCATIONS AS SELECT * FROM HR.LOCATIONS;
CREATE TABLE DEPARTMENTS AS SELECT * FROM HR.DEPARTMENTS;
CREATE TABLE EMPLOYEES AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE JOB_HISTORY AS SELECT * FROM HR.JOB_HISTORY;
CREATE TABLE JOBS AS SELECT * FROM HR.JOBS;
CREATE TABLE JOB_GRADES AS SELECT * FROM HR.JOB_GRADES;
CREATE TABLE PRODUCTS AS SELECT * FROM HR.PRODUCTS;
CREATE TABLE SALES AS SELECT * FROM HR.SALES;

ALTER TABLE REGIONS ADD PRIMARY KEY (REGION_ID);
ALTER TABLE COUNTRIES ADD PRIMARY KEY (COUNTRY_ID);
ALTER TABLE LOCATIONS ADD PRIMARY KEY (LOCATION_ID);
ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPARTMENT_ID);
ALTER TABLE EMPLOYEES ADD PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY ADD CONSTRAINT PK_job_history PRIMARY KEY (EMPLOYEE_ID, START_DATE);
ALTER TABLE JOBS ADD PRIMARY KEY (JOB_ID);
ALTER TABLE SALES ADD PRIMARY KEY (SALE_ID);
ALTER TABLE PRODUCTS ADD PRIMARY KEY (PRODUCT_ID);

ALTER TABLE COUNTRIES ADD FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID);
ALTER TABLE LOCATIONS ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
ALTER TABLE JOB_HISTORY ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID);
ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID);
ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE SALES ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
ALTER TABLE SALES ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID);


SELECT CONCAT(LAST_NAME, SALARY) AS WYNAGRODZENIE FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (20, 50) AND SALARY BETWEEN 2000 AND 7000 ORDER BY LAST_NAME;

SELECT HIRE_DATE, LAST_NAME, &INPUT_COLUMN AS INPUT_COL FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL AND HIRE_DATE BETWEEN '2005-01-01' AND '2005-12-31' 
ORDER BY INPUT_COL;

SELECT CONCAT(FIRST_NAME, LAST_NAME) AS NAME, SALARY, PHONE_NUMBER FROM EMPLOYEES 
WHERE LAST_NAME LIKE '__E%' OR LAST_NAME LIKE '__e%' AND FIRST_NAME LIKE '%&INPUT_NAME%' ORDER BY 1 DESC, 2 ASC;

SELECT FIRST_NAME, LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS LICZBA_MIESIECY,
CASE
   WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) < 150 THEN SALARY * 0.1
   WHEN ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) BETWEEN 150 AND 200 THEN SALARY * 0.2
   ELSE SALARY * 0.3
END AS WYSOKOSC_DODATKU
FROM EMPLOYEES ORDER BY LICZBA_MIESIECY;

SELECT DEPARTMENT_ID, ROUND(SUM(SALARY)) AS SUMA_ZAROBKOW, ROUND(AVG(SALARY)) AS SREDNIA FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID 
HAVING MIN(SALARY)>5000) GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME, J.JOB_ID, L.CITY
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE L.CITY = 'Toronto';

SELECT CONCAT(E.FIRST_NAME, E.LAST_NAME) AS PRACOWNIK, 
CONCAT(WP.FIRST_NAME, WP.LAST_NAME) AS WSPOLPRACOWNICY 
FROM EMPLOYEES E JOIN EMPLOYEES WP ON E.DEPARTMENT_ID=WP.DEPARTMENT_ID 
WHERE E.FIRST_NAME = 'Jennifer' AND E.EMPLOYEE_ID!=WP.EMPLOYEE_ID;

SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID IS NULL;

SELECT CONCAT(E.FIRST_NAME, E.LAST_NAME) AS NAME, E.JOB_ID, D.DEPARTMENT_NAME, E.SALARY, J.GRADE 
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOB_GRADES J ON E.SALARY BETWEEN J.MIN_SALARY AND J.MAX_SALARY;

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (
    SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME LIKE '%u%');
